#!/bin/sh
#
#   backen - parsing of md-broetchen to create finished html-brot
#   USAGE: backen <public | private>
#
#   Copyright (C) 2015 Jonathan Kuhse
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

BACKWAREN="$(pwd)/backwaren"
MARKDOWN_TOOL="$BACKWAREN/md2html.awk"
SAFRAN_INDEX_TOOL="$BACKWAREN/safran"
SKELETONS_DIR="$BACKWAREN/skel"
BRANCH="$1"

source ./backwaren/environment

case $BRANCH in
	"private") DEPLOYMENT_DIR=$PRIVATE_DEPLOYMENT_DIR; echo "deploying into private space";;
	"public") echo "deploying into public space";;
esac

rsync -raq --exclude='*.markdown' --exclude='*.md' --exclude='.git' $WORKNBUILD_DIR/ $DEPLOYMENT_DIR/

case $DEPLOYMENT_DIR in
	/*) DEPLOYMENT_DIR=$DEPLOYMENT_DIR;;
	*) DEPLOYMENT_DIR=$(pwd)/$DEPLOYMENT_DIR;;
esac

cd $WORKNBUILD_DIR

# butter with html
for file in $(find . -name '*.md'); do
	newFileName=$DEPLOYMENT_DIR/$(echo $file | sed 's/\(.*\.\)md/\1html/')
	echo "parsing $newFileName"
	cp $SKELETONS_DIR/header $newFileName
	$MARKDOWN_TOOL $file >> $newFileName
	cat $SKELETONS_DIR/footer >> $newFileName
done

# safran indexing
cd $BACKWAREN
$SAFRAN_INDEX_TOOL $DEPLOYMENT_DIR/pages > $DEPLOYMENT_DIR/index.html
