#!/bin/sh
#
#   backen - parsing of md-broetchen to create finished html-brot
#   USAGE: backen <public | private>
#
#   Copyright (C) 2015 Jonathan Kuhse
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

BACKWAREN="$(pwd)/backwaren"
MARKDOWN_TOOL="/usr/bin/env awk -f $BACKWAREN/md2html.awk"
SAFRAN_INDEX_TOOL="$BACKWAREN/safran"
SKELETONS_DIR="$BACKWAREN/skel"
BRANCH="$1"

. ./backwaren/environment

case $BRANCH in
	"private") DEPLOYMENT_DIR=$DEPLOYMENT_DIR_PRIVATE; echo "deploying into private space";;
	"public") echo "deploying into public space";;
esac

rsync -raq --exclude='*.markdown' --exclude='*.md' --exclude='.git' $WORKINGCOPY/ $DEPLOYMENT_DIR/

case $DEPLOYMENT_DIR in
	/*) DEPLOYMENT_DIR=$DEPLOYMENT_DIR;;
	*) DEPLOYMENT_DIR=$(pwd)/$DEPLOYMENT_DIR;;
esac

cd $WORKINGCOPY
rm -rf $DEPLOYMENT_DIR/pages/*
mkdir -p $DEPLOYMENT_DIR/pages

# butter with html
for file in $(find . -name '*.md'); do
	newFileName=$DEPLOYMENT_DIR/$(echo $file | sed 's/\(.*\.\)md/\1html/')
	### TODO
	filename=$(basename $newFileName)
        date=$(echo $filename | cut -d. -f1)
        topic=$(echo $filename | cut -d. -f2 | sed 's!_! !g')
        author=$(echo $filename | cut -d. -f3 | sed 's!_! !g')

	echo "parsing $newFileName"
	cp $SKELETONS_DIR/header $newFileName
	
	echo "
        <p class=article>
          $topic<br><span class=timestamp>$date | $author</span>
        </p>
	<hr>
        " >> $newFileName



	$MARKDOWN_TOOL $file >> $newFileName
	cat $SKELETONS_DIR/footer >> $newFileName
done

echo "changing access mode ..."

# safran indexing
cd $BACKWAREN
$SAFRAN_INDEX_TOOL $DEPLOYMENT_DIR/pages > $DEPLOYMENT_DIR/index.html

chmod -R 755 $DEPLOYMENT_DIR
